name: Build

on:
  push:
    branches: master

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Create Executable
          uses: sayyid5416/pyinstaller@v1
          with:
            python_ver: '3.12'
            spec: 'main.py'
            requirements: 'requirements.txt'
            upload_exe_with_name: 'SerialToUdpTranslatorV1.0'
            options: --onefile, --name "SerialToUdpTranslatorV1.0", --windowed, 