name: Build

on:
  push:
    branches: master

jobs:
    build-exe:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v4
          with:
            python-version: "3.12"
        - name: Install redwrench
          shell: bash -l {0}
          run: |
            pip3 install .
        - name: install PyInstaller
          shell: bash -l {0}
          run: |
            pip3 install pyinstaller==6.6.0
        - name: Build Pyinstaller .exe (macOS and Linux)
          if: matrix.os != 'windows-latest'
          shell: bash -l {0}
          run: |
            pyinstaller -n redwrench --onefile --windowed main.py
        - name: Build Pyinstaller .exe (Windows)
          if: matrix.os == 'windows-latest'
          shell: bash -l {0}
          run: |
            pyinstaller -n redwrench --onefile main.py
        - uses: vimtor/action-zip@v1
          with:
            files: dist/
            recursive: false
            dest: ${{ matrix.os }}-${{github.ref_name}}.zip
        - uses: softprops/action-gh-release@v1
          with:
            files: ${{ matrix.os }}-${{github.ref_name}}.zip